version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    # Wait for db container to finish setting up postgres
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./scripts/entrypoint.sh'
    depends_on:
      - db
  db:
    image: "postgres"
    restart: always
    ports:
      - "5001:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./tests/fixtures:/sql
