version: "3"
services:
  web:
    volumes:
      - ./:/app
    # Wait for db container to finish setting up postgres
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; ./scripts/entrypoint.sh'