# ERROR CODES
INTERNAL_SERVER_ERROR_CODE="INTERNAL_SERVER_ERROR"
NOT_FOUND_ERROR_CODE="NOT_FOUND_ERROR"

# ERROR MESSAGES
INTERNAL_SERVER_ERROR_MSG='Internal Server Error'
NOT_FOUND_ERROR_MSG='Not Found'
