"""Remove unique requirement for exercise name

Revision ID: 208419fdc870
Revises: 1b948d2fa49c
Create Date: 2020-09-12 13:37:43.194588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '208419fdc870'
down_revision = '1b948d2fa49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_name', table_name='exercise')
    op.create_index(op.f('ix_exercise_name'), 'exercise', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_name'), table_name='exercise')
    op.create_index('ix_exercise_name', 'exercise', ['name'], unique=True)
    # ### end Alembic commands ###
