"""creates workoutExercise table

Revision ID: 211a741538ed
Revises: d51a6b8bdc31
Create Date: 2020-02-22 23:01:03.171739

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '211a741538ed'
down_revision = 'd51a6b8bdc31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_exercise',
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('workout_weights', postgresql.ARRAY(sa.Float()), nullable=False),
    sa.Column('workout_reps', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('rest_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('workout_id', 'exercise_id')
    )
    op.create_index(op.f('ix_workout_exercise_exercise_id'), 'workout_exercise', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_workout_exercise_workout_id'), 'workout_exercise', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_exercise_workout_id'), table_name='workout_exercise')
    op.drop_index(op.f('ix_workout_exercise_exercise_id'), table_name='workout_exercise')
    op.drop_table('workout_exercise')
    # ### end Alembic commands ###
