"""add author field to exercise

Revision ID: 2f849a7e6f1c
Revises: 551aa4724636
Create Date: 2020-08-30 17:12:04.118955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f849a7e6f1c'
down_revision = '551aa4724636'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('author', sa.String(), nullable=False))
    op.create_index(op.f('ix_workout_author'), 'workout', ['author'], unique=False)
    op.create_foreign_key('workout_author_id', 'workout', 'stronk_user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('workout_author_id', 'workout', type_='foreignkey')
    op.drop_index(op.f('ix_workout_author'), table_name='workout')
    op.drop_column('workout', 'author')
    # ### end Alembic commands ###
