"""add author field to exercise

Revision ID: 551aa4724636
Revises: d873ed5a113c
Create Date: 2020-07-30 23:15:02.243874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '551aa4724636'
down_revision = 'd873ed5a113c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('author', sa.String(), nullable=False))
    op.create_index(op.f('ix_exercise_author'), 'exercise', ['author'], unique=False)
    op.create_foreign_key('exercise_author_id', 'exercise', 'stronk_user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_author_id', 'exercise', type_='foreignkey')
    op.drop_index(op.f('ix_exercise_author'), table_name='exercise')
    op.drop_column('exercise', 'author')
    # ### end Alembic commands ###
