"""create workout table

Revision ID: 675ed0ac2f6a
Revises: 5a2a4aec69c5
Create Date: 2020-02-01 12:54:06.549602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675ed0ac2f6a'
down_revision = '5a2a4aec69c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('projected_time', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_name'), 'workout', ['name'], unique=False)
    op.drop_constraint('author_id', 'program', type_='foreignkey')
    op.create_foreign_key(None, 'program', 'user', ['author'], ['id'])
    op.drop_constraint('current_program_id', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'program', ['current_program'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('current_program_id', 'user', 'program', ['current_program'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'program', type_='foreignkey')
    op.create_foreign_key('author_id', 'program', 'user', ['author'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_workout_name'), table_name='workout')
    op.drop_table('workout')
    # ### end Alembic commands ###
