"""create workout table

Revision ID: 675ed0ac2f6a
Revises: 5a2a4aec69c5
Create Date: 2020-02-01 12:54:06.549602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '675ed0ac2f6a'
down_revision = '5a2a4aec69c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=False),
                    sa.Column('projected_time', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_workout_name'), 'workout', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_name'), table_name='workout')
    op.drop_table('workout')
    # ### end Alembic commands ###
