"""removes_fk_constaint_on_exercise_author

Revision ID: 7273110a4617
Revises: 89629adb8459
Create Date: 2020-09-09 23:54:30.858027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7273110a4617'
down_revision = '89629adb8459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('exercise_author_id', 'exercise', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('exercise_author_id', 'exercise', 'stronk_user', ['author'], ['id'])
    # ### end Alembic commands ###
