"""adds unique author and title constraint to program

Revision ID: 89629adb8459
Revises: 1b948d2fa49c
Create Date: 2020-09-05 00:45:33.287906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89629adb8459'
down_revision = '1b948d2fa49c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_program_names_for_author', 'program', ['author', 'name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_program_names_for_author', 'program', type_='unique')
    # ### end Alembic commands ###
