"""adds scheduled date to program workout

Revision ID: d873ed5a113c
Revises: a746f816802c
Create Date: 2020-07-17 18:17:16.539561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd873ed5a113c'
down_revision = 'a746f816802c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('scheduled_time', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workout', 'scheduled_time')
    # ### end Alembic commands ###
