"""create program workouts table

Revision ID: e2b92f1dd2c3
Revises: bd83c2c60694
Create Date: 2020-04-25 18:41:33.492701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b92f1dd2c3'
down_revision = 'bd83c2c60694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('program_workouts',
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.ForeignKeyConstraint(['workout_id'], ['workout.id'], ),
    sa.PrimaryKeyConstraint('program_id', 'workout_id')
    )
    op.create_index(op.f('ix_program_workouts_program_id'), 'program_workouts', ['program_id'], unique=False)
    op.create_index(op.f('ix_program_workouts_workout_id'), 'program_workouts', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_program_workouts_workout_id'), table_name='program_workouts')
    op.drop_index(op.f('ix_program_workouts_program_id'), table_name='program_workouts')
    op.drop_table('program_workouts')
    # ### end Alembic commands ###
